version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # or 16, 18
    commands:
      - echo "Installing dependencies"
      
  pre_build:
    commands:
      - echo "Pre-build phase"
      - npm install
      
  build:
    commands:
      - echo "Build phase started"
      - npm run build || echo "No build script found"
      
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  name: BuildArtifact
